### ISSUE TITLE
Repeated password prompts

### ISSUE THREAD

**Issue by peterjenkins** [inconshreveable/ngrok#146]
Here's my config:

```
auth_token: <snip>
tunnels:
 ssh:
  proto: 
   tcp: 22
 teamcity:
  hostname: "<snip>"
  auth: "<snip>:"
  proto:
   http: 10.88.189.23:8111
```

So I'm using a custom white label domain. I get repeated password prompts when trying to log in, one after the other. But some of them say ngrok, and some of them say TeamCity.

(I'm using this in front of team city.) But I've tried the password I set in ngrok and also the team city password, seems like I'm doing something wrong. Also if I disable the ngrok authentication and log into Team City, then it works OK, even after I re-enable the ngrok auth.

I'm sure there's more digging I can do to try to understand what's going on here, but any ideas for what might be causing it?
