### ISSUE TITLE
Disable custom domain in config

### ISSUE THREAD

**Issue by bazilio91** [inconshreveable/ngrok#159]
It would be great if I can disable automatic subdomain generation from tunnel name. Tried `false`, `null`, `""` for subdomain property, server still asking for account.

Config example:
```yaml
auth_token: null
tunnels:
  node:
    subdomain: ""
    proto:
      http: 9500
```
