### ISSUE TITLE
The plain HTTP request was sent to HTTPS port

### ISSUE THREAD

**Issue by ianwalter** [inconshreveable/ngrok#227]
I'm running this:
```
ngrok -hostname=dev.myhostname.io -proto=https 192.168.59.103:443
```
When I go to https://dev.myhostname.io nginx returns a 400 error saying "The plain HTTP request was sent to HTTPS port"

If I add dev.myhostname.io to my hosts file and navigate there or to the ip address without ngrok running, the site displays just fine.

**Comment by joelash** [comment]
@ianwalter have you made any progress with this? Looks like you're running you nginx in a docker that you're trying to get ngrok to talk to?

Today I was (and sort of still am) struggling with the same setup. I have mine working requests that I make both from my machine and from a separate machine, however the endpoint I'm setting up if for twilio, a third party service, to hit. When twilio makes the request to my endpoint I'm getting this error again, but cannot figure out why. 

My `~/.ngrok/ngrok.yml` looks like

```yml
authtoken: MY_AUTH_TOKEN
tunnels:
  my-nginx:
    proto: tls
    hostname: dev.myhostname.com
    addr: 192.168.59.103:443
```

__Note:__ This require ngrok 2.0


Hope this helps you a tad and maybe you'll be able to point me to what I'm going wrong.
