### ISSUE TITLE
Configuration file without custom subdomain

### ISSUE THREAD

**Issue by Grafikart** [inconshreveable/ngrok#248]
Hi,

I would like to use yml configuration file but I can't set subdomain to false, and the configuration parser set a subdomain based on tunnel name (only for paid subscriptions)

https://github.com/inconshreveable/ngrok/blob/master/src/ngrok/client/config.go#L124

It would be nice being able to do something like that : 

```
tunnels:
  website:
    addr: 80
    proto: http
    subdomain: false
```
