### ISSUE TITLE
Configured tunnels not working

### ISSUE THREAD

**Issue by pyhedgehog** [inconshreveable/ngrok#258]
I have following configuration:
```yaml
authtoken: xxxxxxxxxxxxxxxxxxxx_xxxxxxxxxxxxxxxxxxxxx
tunnels:
  ssh:
    proto: tcp
    addr: 22
  http:
    proto: http
    addr: 5000
```
If I'm starting `ngrok start ssh`, `ngrok tcp 22` or `ngrok http 5000` everything is fine.
If I'm starting `ngrok start http` or `ngrok start --all` it's fails with:
`Tunnel session failed: Custom subdomains are only available for paid plans.`...

It's obviously error as tunnels configured without subdomain.
