### ISSUE TITLE
Reporting tunnel session failed when not using a custom subdomain

### ISSUE THREAD

**Issue by randombitsUK** [inconshreveable/ngrok#296]
Hi,

I'm using ngrok 2.0.19 on Windows 7 to target a virtual machine I'm running.

My default config file is
```yaml
authtoken: "..."
http_proxy: "http://proxy:80"
tunnels:
  www:
    proto: http
    addr: 80
    host_header: www.sandbox.local:80
  static:
    proto: http
    addr: 80
    host_header: static.sandbox.local:80
```

Running 'ngrok start www' results in an error "Tunnel session failed: Custom subdomains are available on any paid plan." However I from the above config I'm not using a custom subdomain?

In addition is it possible to rewrite two host headers. i.e. I have a page on www.sandbox.local:80 that references static.sandbox.local:80, can I serve both at the same time through a single ngrox endpoint?
