### ISSUE TITLE
How to keep source (original) IP?

### ISSUE THREAD

**Issue by whitecolor** [inconshreveable/ngrok#322]
This is config of my connection:
```
  mytest:
    proto: http
    addr: 127.0.0.1:2000
    inspect: false
    host_header: "rewrite"
```

But my server detemins request IP as `127.0.0.1` is it possible to have source IP in request? I tried to remove `host_header: "rewrite"` but it doesn't work at all, should it?
