### ISSUE TITLE
ngrok client background run

### ISSUE THREAD

**Issue by tianzhenyun** [inconshreveable/ngrok#348]
How can i background run ngrok client (R6300v2 merlin) ,thanks all~
I want to remote control my router (include web/ssh....)
here is my config file:
```
server_addr: xxx.xxx:4443
trust_host_root_certs: false
tunnels:
    http:
        proto:
            http: 80
        subdomain: pi
    https:
        proto:
            https: 443
        subdomain: web
    ssh:
        remote_port: 222
        proto:
            tcp: 22
```
