### ISSUE TITLE
use localdomains instead of port

### ISSUE THREAD

**Issue by guns2410** [inconshreveable/ngrok#356]
I have gone through the documentation, but was not able to find an answer to this.

I am using [hotel](https://www.npmjs.com/package/hotel) for development which gives local domains to work with using an Automatic Proxy Configuration

However, when I try to use the local domain to tunnel, ngrok does not identify it as an address. Here is the ngrok configuration file.

```YAML
tunnels:
  server-dev:
    addr: http://server.dev
    proto: http
```

When the tunnel url is called, I get an error 502 Bad Gateway and the screenshot for the error message when trying to access in browser

<img width="586" alt="screen shot 2016-07-25 at 9 34 11 pm" src="https://cloud.githubusercontent.com/assets/1809012/17108072/9a28fefe-52af-11e6-8506-c95b539f6ee2.png">

**Comment by inconshreveable** [comment]
Try:
```
tunnels
  server-dev:
    addr: server.dev:80
    host_header: rewrite
    proto: http
```

closing as this is a 2.x issue
