### ISSUE TITLE
Region won't apply from yml

### ISSUE THREAD

**Issue by agrath** [inconshreveable/ngrok#417]
When I put a region tag in the YML config file, it appears to not be applied in the connected tunnel. Works fine if I specify region as a command line parameter.

```
tunnels:
  testregion:
    proto: http
    addr: 8.8.8.8:80
    subdomain: test-region
    host_header: test-region.com
    region: au
```

> ngrok start testregion
![image](https://cloud.githubusercontent.com/assets/78284/25597629/f07aea64-2f23-11e7-95e1-a76f99f03dd5.png)

> ngrok start testregion -region au
![image](https://cloud.githubusercontent.com/assets/78284/25597641/021a6222-2f24-11e7-8b54-0104283aff66.png)
