### ISSUE TITLE
Environment variables in config yml

### ISSUE THREAD

**Issue by jaredmoody** [inconshreveable/ngrok#55]
Is is possible to insert variables (like perhaps env variables) into the config? 

I'd like to do something like the following to prevent collisions and standardize a config file I could check into source control for my project:

```
tunnels:
  client:
    subdomain: "<%= ENV['user'] %>-myapp"
    proto:
      http: 80
```

Or is there a better way to accomplish this?
