### ISSUE TITLE
(self-hosted) ngrok doesn't work with certs issued by GoDaddy 

### ISSUE THREAD

**Issue by vlebedev** [inconshreveable/ngrok#56]
I'm using a private key and wildcard certificate issued for my domain by godaddy. 

```
$ sudo bin/ngrokd -domain="mydomain.ru" -tlsCrt="/home/jdoe/keys/mydomain.ru.crt" -tlsKey="/home/jdoe/keys/mydomain.ru.key"
```

Ngrokd starts normally, though on a client I have the following error:

```
[EROR] control recovering from failure x509: certificate signed by unknown authority
```

I run the client with the following options:

```
$ ngrok -log=stdout start charlie
```

Here is the contents of my .ngrok file:

```
server_addr: ngrok.mydomain.ru:4443
trust_host_root_certs: true
  tunnels:
    charlie:
      proto:
        http: 5000
```
