### ISSUE TITLE
Add support for project-wise config files and default tunnels

### ISSUE THREAD

**Issue by larrybolt** [inconshreveable/ngrok#61]
The few features I miss is the ability to have project-wise config files containing the tunnels that need to be initiated for the project.

For instance, in my project directory I have next:
```YAML
# ngrok config, load using: ngrok -config ngrok.yaml start default
tunnels:
    default:
        hostname: "project.example.com"
        proto:
            http: 80
```
What currently stops me to do this is that:
* You seem to be unable to load both the `~/.ngrok` config file and a custom one, and allowing my personal auth_token to appear in my repo is something I'd rather not do.
* I still always have to specify the tunnel, and there is not 'default' choice.
* Getting the public forwarding url is difficult unless specifying, for which you again need to be able to set your auth_token, and using apache vhosts with a dynamic hostname like that is a bit difficult.
* Wildchars in custom domain names would make this soo much easier, eg.: `*.dev.example.com`

My current fix:
```bash
alias ngrok="ngrok -authtoken $(cat ~/.ngrok |cut -d' ' -f2-)"
alias localtunnel="ngrok -config ngrok.yaml start default"
```
The only drawbacks are I need to both setup a vhost (which in my case is just a symlink, but that depends on how your development environment is setup, and add the hostname to my ngrok dashboard, which so far is the main annoyance for me.
