### ISSUE TITLE
authtoken in yml not being used

### ISSUE THREAD

**Issue by dsshap** [inconshreveable/ngrok#69]
I created a yml config file with authtoken, but the value is not being picked up,

[12/26/13 12:55:31] [DEBG] [ctl:5b2bc3f8] Writing message: {"Type":"Auth","Payload":{"Version":"2","MmVersion":"1.6","User":"","Password":"","OS":"darwin","Arch":"amd64","ClientId":""}}

When i use -authtoken XXXXXX everything works great.

Below is my yaml

``` yaml
authtoken: XXXX
inspect_addr: "0.0.0.0:8888"
test:
  notifications:
    subdomain: "test"
    proto:
      http: 9295
```

./ngrok -log=stdout -config=ngrok.yml start test
