### ISSUE TITLE
Header X-Forwarded-Proto not being passed

### ISSUE THREAD

**Issue by eliseumds** [inconshreveable/ngrok#696]
Is it just me or this header stopped being passed? Now my ExpressJS session cookie library is complaining about an unencrypted connection, can't trust the proxy. I'm only getting `X-Forwarded-For`. I changed nothing in the config:

```
authtoken: XXXXX
tunnels:
  shopify:
    proto: http
    addr: localhost:4900
    hostname: my_static_id.au.ngrok.io
```

I tried with `host_header: rewrite` as well.
