### ISSUE TITLE
ngrok authtoken command adds extra tunnel block to ngrok.yml

### ISSUE THREAD

**Issue by Distortedlogic** [inconshreveable/ngrok#734]
ngrok.yml file before running `ngrok authtoken ${ngrok_auth_token}`
```
tunnels:
  backend:
    proto: http
    subdomain: memehub-backend
    addr: backend:5000
    bind-tls: true
    inspect: false
```

After, console logs `Authtoken saved to configuration file: /root/.ngrok2/ngrok.yml`

and this is the new ngrok.yml.
Note the extra `tunnel:` breaks ngrok using the yml file
```
authtoken: auth_toke_inserted
tunnels:
   backend:
     tunnel:
       inspect: false
       addr: backend:5000
       subdomain: memehub-backend
```
