### ISSUE TITLE
Can i tunnel email?

### ISSUE THREAD

**Issue by stefanorossiti** [inconshreveable/ngrok#737]
I am under CGNAT and i am using ngrok to tunnel pretty much every private service i have, but i cannot find a way to receive email. I can send them but any received email fails to be tunneled. 

This is my actual configuration:

```
region: eu
console_ui: true
update: true
update_channel: stable

tunnels:
  wild_rs_tls:
    proto: tls
    hostname: '*.rossistefano.ch'
    addr: <reverse proxy ip>
    crt: fc.pem
    key: pk.pem
  #git ssh
  git_rs_ssh:
    proto: tcp
    remote_addr: <rem.ip>
    addr: <another_ip>
```

This will allow me to have a wildcard https tunnel and a SSL tunnel for SSH. 
But i find no information in the documentation on how i should to configure ngrok/dns to tunnel incoming emails.
