### ISSUE TITLE
Cannot serve https endpoint with valid TLS termination

### ISSUE THREAD

**Issue by orty** [inconshreveable/ngrok#782]
Hello,

I cannot find a way to manage the https + TLS configuration. Everything that I tried ends up either with the regular certificate warning, or with an `ERR_EMPTY_RESPONSE` error. Here are the steps I followed :

- created a domain on Azure `my-domain.com`
- registered the domain in my paid ngrok plan, added the CNAME in Azure `xxxxxxxxx.cname.eu.ngrok.io`
- created a certificate in Azure, validated it and downloaded the `.pfx` certificate file
- generated a `.crt` and a passwordless `.key` files
- specified my `ngrok.yml` as follows

```
authtoken: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
region: eu
update: true
tunnels:
    api:
        proto: tls
        addr: localhost:7071
        hostname: my-domain.com
        host-header: localhost:7071
        key: path/to/certificate.key
        crt: path/to/certificate.crt
```

On my computer, VS is serving the webservice (an Azure function) over `https` at `https://localhost:7071`

My previous configuration was working, I just wanted to get rid of the certificate warnings.

The previous one was 

```
    api:
        proto: http
        addr: https://localhost:7071
        hostname: my-domain.com
        host-header: localhost:7071
```

What did I do wrong ?
