### ISSUE TITLE
Ngrok can't read config for ports

### ISSUE THREAD

**Issue by Pokeman2003** [inconshreveable/ngrok#787]
So, I'm currently setting up a Raspberry Pi to be my testing server and to host code backups over SFTP(I really don't like Git). After tussling with Hamachi for a bit, I was recommended Ngrok. Installing Ngrok, I was able to open a port just fine without a config file. It was at this point that I decided that I'd want multiple ports open. I read through the documentation, and wrote this config file.
```
authtoken: (REDACTED)
tunnels:
  httpnorm:
    proto: http
    addr: 80
  httptest:
    proto: http
    addr: 69420
  sftp1:
    proto: tcp
    addr: 22
  sftp2:
    proto: tcp
    addr: 21

```
Now, this is a completely fine YAML file, I've even checked it for error twice, so the formatting doesn't appear to be an issue. However, upon running the command "./ngrok start -config='ngroksetup.yml' sftp1", I get the following output.
```
ERROR: Tunnel 'sftp1' is not defined in the config files.
ERROR: Tunnels available:
ERROR: Config files read: [ngroksetup.yml]
```
That isn't correct, because ngroksetup.yml(which is on the root of the filesystem) clearly has listed tunnels. Why is it incorrectly interpreting the setup file? By the ways, I already tried, "sudo ./ngrok start sftp1" also doesn't work, even with a copy of my config at the specified home directory.
