### ISSUE TITLE
Can't run multiple ngrok tunnels using config file

### ISSUE THREAD

**Issue by Githamza** [inconshreveable/ngrok#818]
I would like to run multiple Ngrok subdomains

I have created an ngrok.yml file.

```
tunnels:
  teams:
    proto: http
    addr: 8000
    subdomain: expl
  jira:
    proto: http
    addr: 8080
    subdomain: expl2
 ```

Then I run `./ngrok start teams -config=ngrok.yml`

I have a Basic plan I have already registres my authtoken.

But I get this message

Only paid plans may bind custom subdomains.

**_Failed to bind the custom subdomain 'explore' for an unauthenticated client. Sign up at: https://dashboard.ngrok.com/signup

If you have already signed up, make sure your authtoken is installed. Your authtoken is available on your dashboard: https://dashboard.ngrok.com/get-started/your-authtoken

ERR_NGROK_305_**

But I'm able to run a single subdomain tunnel using command : `./ngrok http -hostname=exple 3000`, it works
