### ISSUE TITLE
Templating in yaml config files

### ISSUE THREAD

**Issue by patcon** [inconshreveable/ngrok#88]
Forked from https://github.com/inconshreveable/ngrok/issues/61

The idea is that a project that wants to bundle a per-project config file can do something to make the custom subdomain reflect the user and feature branch, to ensure there are no conflicts (forgive the ruby :)

```
tunnels:
  client:
    subdomain: "<%= `git rev-parse --abbrev-ref HEAD`.chomp %>--<%= `git config github.user`.chomp %>"
    proto:
      http: 8537
```

And this would mean my current branch would show up at http://patcon--2045-facebook-share-img.ngrok.com for anyone else helping me troubleshoot (assuming I always expose my local vagrant env while working on it, which might be a cool habit for an open company like Gittip)
